/**
 * Sample Bazel dependency graph for demo/testing.
 */
export const SAMPLE_DOT = `digraph mygraph {
  node [shape=box];
  "//app/server:main" -> "//app/server:lib"
  "//app/server:main" -> "//lib/config:config"
  "//app/server:lib" -> "//lib/http:server"
  "//app/server:lib" -> "//lib/db:client"
  "//app/server:lib" -> "//lib/config:config"
  "//app/server:lib" -> "//lib/logging:logger"
  "//lib/http:server" -> "//lib/http:router"
  "//lib/http:server" -> "//lib/http:middleware"
  "//lib/http:server" -> "//lib/logging:logger"
  "//lib/http:router" -> "//lib/http:types"
  "//lib/http:middleware" -> "//lib/http:types"
  "//lib/http:middleware" -> "//lib/auth:validator"
  "//lib/auth:validator" -> "//lib/auth:jwt"
  "//lib/auth:validator" -> "//lib/config:config"
  "//lib/auth:jwt" -> "//third_party/jose:jose"
  "//lib/auth:jwt" -> "//lib/logging:logger"
  "//lib/db:client" -> "//lib/db:pool"
  "//lib/db:client" -> "//lib/db:migrations"
  "//lib/db:client" -> "//lib/logging:logger"
  "//lib/db:pool" -> "//third_party/pg:pg"
  "//lib/db:pool" -> "//lib/config:config"
  "//lib/db:migrations" -> "//lib/db:pool"
  "//lib/db:migrations" -> "//lib/logging:logger"
  "//lib/logging:logger" -> "//lib/logging:formatter"
  "//lib/logging:logger" -> "//lib/config:config"
  "//lib/logging:formatter" -> "//third_party/chalk:chalk"
  "//lib/config:config" -> "//third_party/dotenv:dotenv"
  "//app/worker:main" -> "//app/worker:processor"
  "//app/worker:main" -> "//lib/config:config"
  "//app/worker:processor" -> "//lib/db:client"
  "//app/worker:processor" -> "//lib/logging:logger"
  "//app/worker:processor" -> "//lib/queue:consumer"
  "//lib/queue:consumer" -> "//lib/queue:connection"
  "//lib/queue:consumer" -> "//lib/logging:logger"
  "//lib/queue:connection" -> "//third_party/amqp:amqp"
  "//lib/queue:connection" -> "//lib/config:config"
  "//app/cli:main" -> "//app/cli:commands"
  "//app/cli:main" -> "//lib/config:config"
  "//app/cli:commands" -> "//lib/db:client"
  "//app/cli:commands" -> "//lib/logging:logger"
  "//app/cli:commands" -> "//third_party/commander:commander"
}`;
